//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4 lokad-codedsl\\Source\\MessageContracts.g 2013-03-21 08:11:24

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 168, 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;
using ConditionalAttribute = System.Diagnostics.ConditionalAttribute;


using Antlr.Runtime.Tree;
using RewriteRuleITokenStream = Antlr.Runtime.Tree.RewriteRuleTokenStream;

namespace  MessageContracts 
{
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4")]
[System.CLSCompliant(false)]
public partial class MessageContractsParser : Antlr.Runtime.Parser
{
	internal static readonly string[] tokenNames = new string[] {
		"<invalid>", "<EOR>", "<DOWN>", "<UP>", "BlockToken", "COMMENT", "CONST", "CommandToken", "DisctionaryToken", "ESC_SEQ", "EXPLICIT", "EXTERN", "EntityDefinition", "EventToken", "ExternToken", "FragmentEntry", "FragmentGroup", "FragmentReference", "HEX_DIGIT", "ID", "IF", "INT", "INTERFACE", "MemberToken", "Modifier", "ModifierDefinition", "NAMESPACE", "NamespaceToken", "OCTAL_ESC", "STRING", "StringRepresentationToken", "TemplateToken", "TypeToken", "UNICODE_ESC", "USING", "UsingToken", "WS", "'('", "')'", "','", "'.'", "';'", "'='", "'{'", "'}'"
	};
	public const int EOF=-1;
	public const int T__37=37;
	public const int T__38=38;
	public const int T__39=39;
	public const int T__40=40;
	public const int T__41=41;
	public const int T__42=42;
	public const int T__43=43;
	public const int T__44=44;
	public const int BlockToken=4;
	public const int COMMENT=5;
	public const int CONST=6;
	public const int CommandToken=7;
	public const int DisctionaryToken=8;
	public const int ESC_SEQ=9;
	public const int EXPLICIT=10;
	public const int EXTERN=11;
	public const int EntityDefinition=12;
	public const int EventToken=13;
	public const int ExternToken=14;
	public const int FragmentEntry=15;
	public const int FragmentGroup=16;
	public const int FragmentReference=17;
	public const int HEX_DIGIT=18;
	public const int ID=19;
	public const int IF=20;
	public const int INT=21;
	public const int INTERFACE=22;
	public const int MemberToken=23;
	public const int Modifier=24;
	public const int ModifierDefinition=25;
	public const int NAMESPACE=26;
	public const int NamespaceToken=27;
	public const int OCTAL_ESC=28;
	public const int STRING=29;
	public const int StringRepresentationToken=30;
	public const int TemplateToken=31;
	public const int TypeToken=32;
	public const int UNICODE_ESC=33;
	public const int USING=34;
	public const int UsingToken=35;
	public const int WS=36;

	#if ANTLR_DEBUG
		private static readonly bool[] decisionCanBacktrack =
			new bool[]
			{
				false, // invalid decision
				false, false, false, false, false, false, false, false, false, false, 
				false
			};
	#else
		private static readonly bool[] decisionCanBacktrack = new bool[0];
	#endif
	public MessageContractsParser(ITokenStream input)
		: this(input, new RecognizerSharedState())
	{
	}
	public MessageContractsParser(ITokenStream input, RecognizerSharedState state)
		: base(input, state)
	{
		OnCreated();
	}
	private ITreeAdaptor adaptor;

	public ITreeAdaptor TreeAdaptor
	{
		get
		{
			return adaptor;
		}

		set
		{
			this.adaptor = value;
		}
	}

	public override string[] TokenNames { get { return MessageContractsParser.tokenNames; } }
	public override string GrammarFileName { get { return "lokad-codedsl\\Source\\MessageContracts.g"; } }


	[Conditional("ANTLR_TRACE")]
	protected virtual void OnCreated() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule(string ruleName, int ruleIndex) {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule(string ruleName, int ruleIndex) {}

	#region Rules

	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_program() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_program() {}

	// $ANTLR start "program"
	// lokad-codedsl\\Source\\MessageContracts.g:32:1: program : ( declaration )+ ;
	[GrammarRule("program")]
	private AstParserRuleReturnScope<object, IToken> program()
	{
		EnterRule_program();
		EnterRule("program", 1);
		TraceIn("program", 1);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    AstParserRuleReturnScope<object, IToken> declaration1 = default(AstParserRuleReturnScope<object, IToken>);


		try { DebugEnterRule(GrammarFileName, "program");
		DebugLocation(32, 1);
		try
		{
			// lokad-codedsl\\Source\\MessageContracts.g:33:2: ( ( declaration )+ )
			DebugEnterAlt(1);
			// lokad-codedsl\\Source\\MessageContracts.g:33:4: ( declaration )+
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(33, 4);
			// lokad-codedsl\\Source\\MessageContracts.g:33:4: ( declaration )+
			int cnt1=0;
			try { DebugEnterSubRule(1);
			while (true)
			{
				int alt1=2;
				try { DebugEnterDecision(1, decisionCanBacktrack[1]);
				int LA1_0 = input.LA(1);

				if ((LA1_0==CONST||LA1_0==EXTERN||(LA1_0>=ID && LA1_0<=IF)||LA1_0==INTERFACE||LA1_0==NAMESPACE||LA1_0==USING))
				{
					alt1 = 1;
				}


				} finally { DebugExitDecision(1); }
				switch (alt1)
				{
				case 1:
					DebugEnterAlt(1);
					// lokad-codedsl\\Source\\MessageContracts.g:33:4: declaration
					{
					DebugLocation(33, 4);
					PushFollow(Follow._declaration_in_program121);
					declaration1=declaration();
					PopFollow();

					adaptor.AddChild(root_0, declaration1.Tree);

					}
					break;

				default:
					if (cnt1 >= 1)
						goto loop1;

					EarlyExitException eee1 = new EarlyExitException( 1, input );
					DebugRecognitionException(eee1);
					throw eee1;
				}
				cnt1++;
			}
			loop1:
				;

			} finally { DebugExitSubRule(1); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("program", 1);
			LeaveRule("program", 1);
			LeaveRule_program();
	    }
	 	DebugLocation(34, 1);
		} finally { DebugExitRule(GrammarFileName, "program"); }
		return retval;

	}
	// $ANTLR end "program"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_declaration() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_declaration() {}

	// $ANTLR start "declaration"
	// lokad-codedsl\\Source\\MessageContracts.g:36:1: declaration : ( modifier_declaration | frag_declaration | type_declaration | entity_declaration | namespace_declaration | extern_declaration | template_declaration | using_declaration );
	[GrammarRule("declaration")]
	private AstParserRuleReturnScope<object, IToken> declaration()
	{
		EnterRule_declaration();
		EnterRule("declaration", 2);
		TraceIn("declaration", 2);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    AstParserRuleReturnScope<object, IToken> modifier_declaration2 = default(AstParserRuleReturnScope<object, IToken>);
	    AstParserRuleReturnScope<object, IToken> frag_declaration3 = default(AstParserRuleReturnScope<object, IToken>);
	    AstParserRuleReturnScope<object, IToken> type_declaration4 = default(AstParserRuleReturnScope<object, IToken>);
	    AstParserRuleReturnScope<object, IToken> entity_declaration5 = default(AstParserRuleReturnScope<object, IToken>);
	    AstParserRuleReturnScope<object, IToken> namespace_declaration6 = default(AstParserRuleReturnScope<object, IToken>);
	    AstParserRuleReturnScope<object, IToken> extern_declaration7 = default(AstParserRuleReturnScope<object, IToken>);
	    AstParserRuleReturnScope<object, IToken> template_declaration8 = default(AstParserRuleReturnScope<object, IToken>);
	    AstParserRuleReturnScope<object, IToken> using_declaration9 = default(AstParserRuleReturnScope<object, IToken>);


		try { DebugEnterRule(GrammarFileName, "declaration");
		DebugLocation(36, 1);
		try
		{
			// lokad-codedsl\\Source\\MessageContracts.g:37:2: ( modifier_declaration | frag_declaration | type_declaration | entity_declaration | namespace_declaration | extern_declaration | template_declaration | using_declaration )
			int alt2=8;
			try { DebugEnterDecision(2, decisionCanBacktrack[2]);
			switch (input.LA(1))
			{
			case IF:
				{
				alt2 = 1;
				}
				break;
			case CONST:
				{
				alt2 = 2;
				}
				break;
			case ID:
				{
				int LA2_3 = input.LA(2);

				if ((LA2_3==42))
				{
					alt2 = 7;
				}
				else if ((LA2_3==Modifier||LA2_3==37))
				{
					alt2 = 3;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 2, 3, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
				}
				break;
			case INTERFACE:
				{
				alt2 = 4;
				}
				break;
			case NAMESPACE:
				{
				alt2 = 5;
				}
				break;
			case EXTERN:
				{
				alt2 = 6;
				}
				break;
			case USING:
				{
				alt2 = 8;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 2, 0, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(2); }
			switch (alt2)
			{
			case 1:
				DebugEnterAlt(1);
				// lokad-codedsl\\Source\\MessageContracts.g:37:4: modifier_declaration
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(37, 4);
				PushFollow(Follow._modifier_declaration_in_declaration134);
				modifier_declaration2=modifier_declaration();
				PopFollow();

				adaptor.AddChild(root_0, modifier_declaration2.Tree);

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// lokad-codedsl\\Source\\MessageContracts.g:38:4: frag_declaration
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(38, 4);
				PushFollow(Follow._frag_declaration_in_declaration139);
				frag_declaration3=frag_declaration();
				PopFollow();

				adaptor.AddChild(root_0, frag_declaration3.Tree);

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// lokad-codedsl\\Source\\MessageContracts.g:39:4: type_declaration
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(39, 4);
				PushFollow(Follow._type_declaration_in_declaration144);
				type_declaration4=type_declaration();
				PopFollow();

				adaptor.AddChild(root_0, type_declaration4.Tree);

				}
				break;
			case 4:
				DebugEnterAlt(4);
				// lokad-codedsl\\Source\\MessageContracts.g:40:4: entity_declaration
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(40, 4);
				PushFollow(Follow._entity_declaration_in_declaration149);
				entity_declaration5=entity_declaration();
				PopFollow();

				adaptor.AddChild(root_0, entity_declaration5.Tree);

				}
				break;
			case 5:
				DebugEnterAlt(5);
				// lokad-codedsl\\Source\\MessageContracts.g:41:4: namespace_declaration
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(41, 4);
				PushFollow(Follow._namespace_declaration_in_declaration154);
				namespace_declaration6=namespace_declaration();
				PopFollow();

				adaptor.AddChild(root_0, namespace_declaration6.Tree);

				}
				break;
			case 6:
				DebugEnterAlt(6);
				// lokad-codedsl\\Source\\MessageContracts.g:42:4: extern_declaration
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(42, 4);
				PushFollow(Follow._extern_declaration_in_declaration160);
				extern_declaration7=extern_declaration();
				PopFollow();

				adaptor.AddChild(root_0, extern_declaration7.Tree);

				}
				break;
			case 7:
				DebugEnterAlt(7);
				// lokad-codedsl\\Source\\MessageContracts.g:43:4: template_declaration
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(43, 4);
				PushFollow(Follow._template_declaration_in_declaration165);
				template_declaration8=template_declaration();
				PopFollow();

				adaptor.AddChild(root_0, template_declaration8.Tree);

				}
				break;
			case 8:
				DebugEnterAlt(8);
				// lokad-codedsl\\Source\\MessageContracts.g:44:4: using_declaration
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(44, 4);
				PushFollow(Follow._using_declaration_in_declaration170);
				using_declaration9=using_declaration();
				PopFollow();

				adaptor.AddChild(root_0, using_declaration9.Tree);

				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("declaration", 2);
			LeaveRule("declaration", 2);
			LeaveRule_declaration();
	    }
	 	DebugLocation(45, 1);
		} finally { DebugExitRule(GrammarFileName, "declaration"); }
		return retval;

	}
	// $ANTLR end "declaration"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_namespace_declaration() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_namespace_declaration() {}

	// $ANTLR start "namespace_declaration"
	// lokad-codedsl\\Source\\MessageContracts.g:47:1: namespace_declaration : NAMESPACE ( ID ( '.' ID )* ) ';' -> ^( NamespaceToken ( ID )* ) ;
	[GrammarRule("namespace_declaration")]
	private AstParserRuleReturnScope<object, IToken> namespace_declaration()
	{
		EnterRule_namespace_declaration();
		EnterRule("namespace_declaration", 3);
		TraceIn("namespace_declaration", 3);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken NAMESPACE10 = default(IToken);
	    IToken ID11 = default(IToken);
	    IToken char_literal12 = default(IToken);
	    IToken ID13 = default(IToken);
	    IToken char_literal14 = default(IToken);

	    object NAMESPACE10_tree = default(object);
	    object ID11_tree = default(object);
	    object char_literal12_tree = default(object);
	    object ID13_tree = default(object);
	    object char_literal14_tree = default(object);
	    RewriteRuleITokenStream stream_41=new RewriteRuleITokenStream(adaptor,"token 41");
	    RewriteRuleITokenStream stream_40=new RewriteRuleITokenStream(adaptor,"token 40");
	    RewriteRuleITokenStream stream_ID=new RewriteRuleITokenStream(adaptor,"token ID");
	    RewriteRuleITokenStream stream_NAMESPACE=new RewriteRuleITokenStream(adaptor,"token NAMESPACE");

		try { DebugEnterRule(GrammarFileName, "namespace_declaration");
		DebugLocation(47, 28);
		try
		{
			// lokad-codedsl\\Source\\MessageContracts.g:48:5: ( NAMESPACE ( ID ( '.' ID )* ) ';' -> ^( NamespaceToken ( ID )* ) )
			DebugEnterAlt(1);
			// lokad-codedsl\\Source\\MessageContracts.g:48:7: NAMESPACE ( ID ( '.' ID )* ) ';'
			{
			DebugLocation(48, 7);
			NAMESPACE10=(IToken)Match(input,NAMESPACE,Follow._NAMESPACE_in_namespace_declaration184);  
			stream_NAMESPACE.Add(NAMESPACE10);

			DebugLocation(48, 17);
			// lokad-codedsl\\Source\\MessageContracts.g:48:17: ( ID ( '.' ID )* )
			DebugEnterAlt(1);
			// lokad-codedsl\\Source\\MessageContracts.g:48:18: ID ( '.' ID )*
			{
			DebugLocation(48, 18);
			ID11=(IToken)Match(input,ID,Follow._ID_in_namespace_declaration187);  
			stream_ID.Add(ID11);

			DebugLocation(48, 21);
			// lokad-codedsl\\Source\\MessageContracts.g:48:21: ( '.' ID )*
			try { DebugEnterSubRule(3);
			while (true)
			{
				int alt3=2;
				try { DebugEnterDecision(3, decisionCanBacktrack[3]);
				int LA3_0 = input.LA(1);

				if ((LA3_0==40))
				{
					alt3 = 1;
				}


				} finally { DebugExitDecision(3); }
				switch ( alt3 )
				{
				case 1:
					DebugEnterAlt(1);
					// lokad-codedsl\\Source\\MessageContracts.g:48:22: '.' ID
					{
					DebugLocation(48, 22);
					char_literal12=(IToken)Match(input,40,Follow._40_in_namespace_declaration190);  
					stream_40.Add(char_literal12);

					DebugLocation(48, 26);
					ID13=(IToken)Match(input,ID,Follow._ID_in_namespace_declaration192);  
					stream_ID.Add(ID13);


					}
					break;

				default:
					goto loop3;
				}
			}

			loop3:
				;

			} finally { DebugExitSubRule(3); }


			}

			DebugLocation(48, 32);
			char_literal14=(IToken)Match(input,41,Follow._41_in_namespace_declaration197);  
			stream_41.Add(char_literal14);



			{
			// AST REWRITE
			// elements: ID
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 49:5: -> ^( NamespaceToken ( ID )* )
			{
				DebugLocation(49, 8);
				// lokad-codedsl\\Source\\MessageContracts.g:49:8: ^( NamespaceToken ( ID )* )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(49, 10);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(NamespaceToken, "NamespaceToken"), root_1);

				DebugLocation(49, 25);
				// lokad-codedsl\\Source\\MessageContracts.g:49:25: ( ID )*
				while ( stream_ID.HasNext )
				{
					DebugLocation(49, 25);
					adaptor.AddChild(root_1, stream_ID.NextNode());

				}
				stream_ID.Reset();

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("namespace_declaration", 3);
			LeaveRule("namespace_declaration", 3);
			LeaveRule_namespace_declaration();
	    }
	 	DebugLocation(49, 28);
		} finally { DebugExitRule(GrammarFileName, "namespace_declaration"); }
		return retval;

	}
	// $ANTLR end "namespace_declaration"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_using_declaration() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_using_declaration() {}

	// $ANTLR start "using_declaration"
	// lokad-codedsl\\Source\\MessageContracts.g:51:1: using_declaration : USING ( ID ( '.' ID )* ) ';' -> ^( UsingToken ( ID )* ) ;
	[GrammarRule("using_declaration")]
	private AstParserRuleReturnScope<object, IToken> using_declaration()
	{
		EnterRule_using_declaration();
		EnterRule("using_declaration", 4);
		TraceIn("using_declaration", 4);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken USING15 = default(IToken);
	    IToken ID16 = default(IToken);
	    IToken char_literal17 = default(IToken);
	    IToken ID18 = default(IToken);
	    IToken char_literal19 = default(IToken);

	    object USING15_tree = default(object);
	    object ID16_tree = default(object);
	    object char_literal17_tree = default(object);
	    object ID18_tree = default(object);
	    object char_literal19_tree = default(object);
	    RewriteRuleITokenStream stream_41=new RewriteRuleITokenStream(adaptor,"token 41");
	    RewriteRuleITokenStream stream_40=new RewriteRuleITokenStream(adaptor,"token 40");
	    RewriteRuleITokenStream stream_USING=new RewriteRuleITokenStream(adaptor,"token USING");
	    RewriteRuleITokenStream stream_ID=new RewriteRuleITokenStream(adaptor,"token ID");

		try { DebugEnterRule(GrammarFileName, "using_declaration");
		DebugLocation(51, 24);
		try
		{
			// lokad-codedsl\\Source\\MessageContracts.g:52:5: ( USING ( ID ( '.' ID )* ) ';' -> ^( UsingToken ( ID )* ) )
			DebugEnterAlt(1);
			// lokad-codedsl\\Source\\MessageContracts.g:52:7: USING ( ID ( '.' ID )* ) ';'
			{
			DebugLocation(52, 7);
			USING15=(IToken)Match(input,USING,Follow._USING_in_using_declaration227);  
			stream_USING.Add(USING15);

			DebugLocation(52, 13);
			// lokad-codedsl\\Source\\MessageContracts.g:52:13: ( ID ( '.' ID )* )
			DebugEnterAlt(1);
			// lokad-codedsl\\Source\\MessageContracts.g:52:14: ID ( '.' ID )*
			{
			DebugLocation(52, 14);
			ID16=(IToken)Match(input,ID,Follow._ID_in_using_declaration230);  
			stream_ID.Add(ID16);

			DebugLocation(52, 17);
			// lokad-codedsl\\Source\\MessageContracts.g:52:17: ( '.' ID )*
			try { DebugEnterSubRule(4);
			while (true)
			{
				int alt4=2;
				try { DebugEnterDecision(4, decisionCanBacktrack[4]);
				int LA4_0 = input.LA(1);

				if ((LA4_0==40))
				{
					alt4 = 1;
				}


				} finally { DebugExitDecision(4); }
				switch ( alt4 )
				{
				case 1:
					DebugEnterAlt(1);
					// lokad-codedsl\\Source\\MessageContracts.g:52:18: '.' ID
					{
					DebugLocation(52, 18);
					char_literal17=(IToken)Match(input,40,Follow._40_in_using_declaration233);  
					stream_40.Add(char_literal17);

					DebugLocation(52, 22);
					ID18=(IToken)Match(input,ID,Follow._ID_in_using_declaration235);  
					stream_ID.Add(ID18);


					}
					break;

				default:
					goto loop4;
				}
			}

			loop4:
				;

			} finally { DebugExitSubRule(4); }


			}

			DebugLocation(52, 28);
			char_literal19=(IToken)Match(input,41,Follow._41_in_using_declaration240);  
			stream_41.Add(char_literal19);



			{
			// AST REWRITE
			// elements: ID
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 53:5: -> ^( UsingToken ( ID )* )
			{
				DebugLocation(53, 8);
				// lokad-codedsl\\Source\\MessageContracts.g:53:8: ^( UsingToken ( ID )* )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(53, 10);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(UsingToken, "UsingToken"), root_1);

				DebugLocation(53, 21);
				// lokad-codedsl\\Source\\MessageContracts.g:53:21: ( ID )*
				while ( stream_ID.HasNext )
				{
					DebugLocation(53, 21);
					adaptor.AddChild(root_1, stream_ID.NextNode());

				}
				stream_ID.Reset();

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("using_declaration", 4);
			LeaveRule("using_declaration", 4);
			LeaveRule_using_declaration();
	    }
	 	DebugLocation(53, 24);
		} finally { DebugExitRule(GrammarFileName, "using_declaration"); }
		return retval;

	}
	// $ANTLR end "using_declaration"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_frag_declaration() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_frag_declaration() {}

	// $ANTLR start "frag_declaration"
	// lokad-codedsl\\Source\\MessageContracts.g:56:1: frag_declaration : CONST ID '=' ID ID ';' -> ^( FragmentEntry ID ID ID ) ;
	[GrammarRule("frag_declaration")]
	private AstParserRuleReturnScope<object, IToken> frag_declaration()
	{
		EnterRule_frag_declaration();
		EnterRule("frag_declaration", 5);
		TraceIn("frag_declaration", 5);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken CONST20 = default(IToken);
	    IToken ID21 = default(IToken);
	    IToken char_literal22 = default(IToken);
	    IToken ID23 = default(IToken);
	    IToken ID24 = default(IToken);
	    IToken char_literal25 = default(IToken);

	    object CONST20_tree = default(object);
	    object ID21_tree = default(object);
	    object char_literal22_tree = default(object);
	    object ID23_tree = default(object);
	    object ID24_tree = default(object);
	    object char_literal25_tree = default(object);
	    RewriteRuleITokenStream stream_42=new RewriteRuleITokenStream(adaptor,"token 42");
	    RewriteRuleITokenStream stream_41=new RewriteRuleITokenStream(adaptor,"token 41");
	    RewriteRuleITokenStream stream_ID=new RewriteRuleITokenStream(adaptor,"token ID");
	    RewriteRuleITokenStream stream_CONST=new RewriteRuleITokenStream(adaptor,"token CONST");

		try { DebugEnterRule(GrammarFileName, "frag_declaration");
		DebugLocation(56, 54);
		try
		{
			// lokad-codedsl\\Source\\MessageContracts.g:57:2: ( CONST ID '=' ID ID ';' -> ^( FragmentEntry ID ID ID ) )
			DebugEnterAlt(1);
			// lokad-codedsl\\Source\\MessageContracts.g:57:4: CONST ID '=' ID ID ';'
			{
			DebugLocation(57, 4);
			CONST20=(IToken)Match(input,CONST,Follow._CONST_in_frag_declaration264);  
			stream_CONST.Add(CONST20);

			DebugLocation(57, 10);
			ID21=(IToken)Match(input,ID,Follow._ID_in_frag_declaration266);  
			stream_ID.Add(ID21);

			DebugLocation(57, 13);
			char_literal22=(IToken)Match(input,42,Follow._42_in_frag_declaration268);  
			stream_42.Add(char_literal22);

			DebugLocation(57, 17);
			ID23=(IToken)Match(input,ID,Follow._ID_in_frag_declaration270);  
			stream_ID.Add(ID23);

			DebugLocation(57, 20);
			ID24=(IToken)Match(input,ID,Follow._ID_in_frag_declaration272);  
			stream_ID.Add(ID24);

			DebugLocation(57, 23);
			char_literal25=(IToken)Match(input,41,Follow._41_in_frag_declaration274);  
			stream_41.Add(char_literal25);



			{
			// AST REWRITE
			// elements: ID, ID, ID
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 57:27: -> ^( FragmentEntry ID ID ID )
			{
				DebugLocation(57, 30);
				// lokad-codedsl\\Source\\MessageContracts.g:57:30: ^( FragmentEntry ID ID ID )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(57, 32);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(FragmentEntry, "FragmentEntry"), root_1);

				DebugLocation(57, 46);
				adaptor.AddChild(root_1, stream_ID.NextNode());
				DebugLocation(57, 49);
				adaptor.AddChild(root_1, stream_ID.NextNode());
				DebugLocation(57, 52);
				adaptor.AddChild(root_1, stream_ID.NextNode());

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("frag_declaration", 5);
			LeaveRule("frag_declaration", 5);
			LeaveRule_frag_declaration();
	    }
	 	DebugLocation(57, 54);
		} finally { DebugExitRule(GrammarFileName, "frag_declaration"); }
		return retval;

	}
	// $ANTLR end "frag_declaration"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_modifier_declaration() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_modifier_declaration() {}

	// $ANTLR start "modifier_declaration"
	// lokad-codedsl\\Source\\MessageContracts.g:59:1: modifier_declaration : IF Modifier '=' ID ( ',' ID )* ';' -> ^( ModifierDefinition Modifier ( ID )* ) ;
	[GrammarRule("modifier_declaration")]
	private AstParserRuleReturnScope<object, IToken> modifier_declaration()
	{
		EnterRule_modifier_declaration();
		EnterRule("modifier_declaration", 6);
		TraceIn("modifier_declaration", 6);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken IF26 = default(IToken);
	    IToken Modifier27 = default(IToken);
	    IToken char_literal28 = default(IToken);
	    IToken ID29 = default(IToken);
	    IToken char_literal30 = default(IToken);
	    IToken ID31 = default(IToken);
	    IToken char_literal32 = default(IToken);

	    object IF26_tree = default(object);
	    object Modifier27_tree = default(object);
	    object char_literal28_tree = default(object);
	    object ID29_tree = default(object);
	    object char_literal30_tree = default(object);
	    object ID31_tree = default(object);
	    object char_literal32_tree = default(object);
	    RewriteRuleITokenStream stream_42=new RewriteRuleITokenStream(adaptor,"token 42");
	    RewriteRuleITokenStream stream_41=new RewriteRuleITokenStream(adaptor,"token 41");
	    RewriteRuleITokenStream stream_ID=new RewriteRuleITokenStream(adaptor,"token ID");
	    RewriteRuleITokenStream stream_Modifier=new RewriteRuleITokenStream(adaptor,"token Modifier");
	    RewriteRuleITokenStream stream_39=new RewriteRuleITokenStream(adaptor,"token 39");
	    RewriteRuleITokenStream stream_IF=new RewriteRuleITokenStream(adaptor,"token IF");

		try { DebugEnterRule(GrammarFileName, "modifier_declaration");
		DebugLocation(59, 73);
		try
		{
			// lokad-codedsl\\Source\\MessageContracts.g:60:2: ( IF Modifier '=' ID ( ',' ID )* ';' -> ^( ModifierDefinition Modifier ( ID )* ) )
			DebugEnterAlt(1);
			// lokad-codedsl\\Source\\MessageContracts.g:60:4: IF Modifier '=' ID ( ',' ID )* ';'
			{
			DebugLocation(60, 4);
			IF26=(IToken)Match(input,IF,Follow._IF_in_modifier_declaration301);  
			stream_IF.Add(IF26);

			DebugLocation(60, 7);
			Modifier27=(IToken)Match(input,Modifier,Follow._Modifier_in_modifier_declaration303);  
			stream_Modifier.Add(Modifier27);

			DebugLocation(60, 16);
			char_literal28=(IToken)Match(input,42,Follow._42_in_modifier_declaration305);  
			stream_42.Add(char_literal28);

			DebugLocation(60, 20);
			ID29=(IToken)Match(input,ID,Follow._ID_in_modifier_declaration307);  
			stream_ID.Add(ID29);

			DebugLocation(60, 23);
			// lokad-codedsl\\Source\\MessageContracts.g:60:23: ( ',' ID )*
			try { DebugEnterSubRule(5);
			while (true)
			{
				int alt5=2;
				try { DebugEnterDecision(5, decisionCanBacktrack[5]);
				int LA5_0 = input.LA(1);

				if ((LA5_0==39))
				{
					alt5 = 1;
				}


				} finally { DebugExitDecision(5); }
				switch ( alt5 )
				{
				case 1:
					DebugEnterAlt(1);
					// lokad-codedsl\\Source\\MessageContracts.g:60:24: ',' ID
					{
					DebugLocation(60, 24);
					char_literal30=(IToken)Match(input,39,Follow._39_in_modifier_declaration310);  
					stream_39.Add(char_literal30);

					DebugLocation(60, 28);
					ID31=(IToken)Match(input,ID,Follow._ID_in_modifier_declaration312);  
					stream_ID.Add(ID31);


					}
					break;

				default:
					goto loop5;
				}
			}

			loop5:
				;

			} finally { DebugExitSubRule(5); }

			DebugLocation(60, 33);
			char_literal32=(IToken)Match(input,41,Follow._41_in_modifier_declaration316);  
			stream_41.Add(char_literal32);



			{
			// AST REWRITE
			// elements: ID, Modifier
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 60:37: -> ^( ModifierDefinition Modifier ( ID )* )
			{
				DebugLocation(60, 40);
				// lokad-codedsl\\Source\\MessageContracts.g:60:40: ^( ModifierDefinition Modifier ( ID )* )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(60, 42);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(ModifierDefinition, "ModifierDefinition"), root_1);

				DebugLocation(60, 61);
				adaptor.AddChild(root_1, stream_Modifier.NextNode());
				DebugLocation(60, 70);
				// lokad-codedsl\\Source\\MessageContracts.g:60:70: ( ID )*
				while ( stream_ID.HasNext )
				{
					DebugLocation(60, 70);
					adaptor.AddChild(root_1, stream_ID.NextNode());

				}
				stream_ID.Reset();

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("modifier_declaration", 6);
			LeaveRule("modifier_declaration", 6);
			LeaveRule_modifier_declaration();
	    }
	 	DebugLocation(60, 73);
		} finally { DebugExitRule(GrammarFileName, "modifier_declaration"); }
		return retval;

	}
	// $ANTLR end "modifier_declaration"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_entity_declaration() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_entity_declaration() {}

	// $ANTLR start "entity_declaration"
	// lokad-codedsl\\Source\\MessageContracts.g:62:1: entity_declaration : lc= INTERFACE ID block '{' ( declaration )* '}' -> ^( EntityDefinition[$lc,\"Block\"] ID block ( declaration )* ) ;
	[GrammarRule("entity_declaration")]
	private AstParserRuleReturnScope<object, IToken> entity_declaration()
	{
		EnterRule_entity_declaration();
		EnterRule("entity_declaration", 7);
		TraceIn("entity_declaration", 7);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken lc = default(IToken);
	    IToken ID33 = default(IToken);
	    IToken char_literal35 = default(IToken);
	    IToken char_literal37 = default(IToken);
	    AstParserRuleReturnScope<object, IToken> block34 = default(AstParserRuleReturnScope<object, IToken>);
	    AstParserRuleReturnScope<object, IToken> declaration36 = default(AstParserRuleReturnScope<object, IToken>);

	    object lc_tree = default(object);
	    object ID33_tree = default(object);
	    object char_literal35_tree = default(object);
	    object char_literal37_tree = default(object);
	    RewriteRuleITokenStream stream_43=new RewriteRuleITokenStream(adaptor,"token 43");
	    RewriteRuleITokenStream stream_INTERFACE=new RewriteRuleITokenStream(adaptor,"token INTERFACE");
	    RewriteRuleITokenStream stream_44=new RewriteRuleITokenStream(adaptor,"token 44");
	    RewriteRuleITokenStream stream_ID=new RewriteRuleITokenStream(adaptor,"token ID");
	    RewriteRuleSubtreeStream stream_declaration=new RewriteRuleSubtreeStream(adaptor,"rule declaration");
	    RewriteRuleSubtreeStream stream_block=new RewriteRuleSubtreeStream(adaptor,"rule block");
		try { DebugEnterRule(GrammarFileName, "entity_declaration");
		DebugLocation(62, 58);
		try
		{
			// lokad-codedsl\\Source\\MessageContracts.g:63:2: (lc= INTERFACE ID block '{' ( declaration )* '}' -> ^( EntityDefinition[$lc,\"Block\"] ID block ( declaration )* ) )
			DebugEnterAlt(1);
			// lokad-codedsl\\Source\\MessageContracts.g:63:4: lc= INTERFACE ID block '{' ( declaration )* '}'
			{
			DebugLocation(63, 6);
			lc=(IToken)Match(input,INTERFACE,Follow._INTERFACE_in_entity_declaration340);  
			stream_INTERFACE.Add(lc);

			DebugLocation(63, 18);
			ID33=(IToken)Match(input,ID,Follow._ID_in_entity_declaration342);  
			stream_ID.Add(ID33);

			DebugLocation(63, 21);
			PushFollow(Follow._block_in_entity_declaration344);
			block34=block();
			PopFollow();

			stream_block.Add(block34.Tree);
			DebugLocation(63, 27);
			char_literal35=(IToken)Match(input,43,Follow._43_in_entity_declaration346);  
			stream_43.Add(char_literal35);

			DebugLocation(63, 31);
			// lokad-codedsl\\Source\\MessageContracts.g:63:31: ( declaration )*
			try { DebugEnterSubRule(6);
			while (true)
			{
				int alt6=2;
				try { DebugEnterDecision(6, decisionCanBacktrack[6]);
				int LA6_0 = input.LA(1);

				if ((LA6_0==CONST||LA6_0==EXTERN||(LA6_0>=ID && LA6_0<=IF)||LA6_0==INTERFACE||LA6_0==NAMESPACE||LA6_0==USING))
				{
					alt6 = 1;
				}


				} finally { DebugExitDecision(6); }
				switch ( alt6 )
				{
				case 1:
					DebugEnterAlt(1);
					// lokad-codedsl\\Source\\MessageContracts.g:63:31: declaration
					{
					DebugLocation(63, 31);
					PushFollow(Follow._declaration_in_entity_declaration348);
					declaration36=declaration();
					PopFollow();

					stream_declaration.Add(declaration36.Tree);

					}
					break;

				default:
					goto loop6;
				}
			}

			loop6:
				;

			} finally { DebugExitSubRule(6); }

			DebugLocation(63, 44);
			char_literal37=(IToken)Match(input,44,Follow._44_in_entity_declaration351);  
			stream_44.Add(char_literal37);



			{
			// AST REWRITE
			// elements: ID, block, declaration
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 64:2: -> ^( EntityDefinition[$lc,\"Block\"] ID block ( declaration )* )
			{
				DebugLocation(64, 5);
				// lokad-codedsl\\Source\\MessageContracts.g:64:5: ^( EntityDefinition[$lc,\"Block\"] ID block ( declaration )* )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(64, 7);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(EntityDefinition, lc, "Block"), root_1);

				DebugLocation(64, 37);
				adaptor.AddChild(root_1, stream_ID.NextNode());
				DebugLocation(64, 40);
				adaptor.AddChild(root_1, stream_block.NextTree());
				DebugLocation(64, 46);
				// lokad-codedsl\\Source\\MessageContracts.g:64:46: ( declaration )*
				while ( stream_declaration.HasNext )
				{
					DebugLocation(64, 46);
					adaptor.AddChild(root_1, stream_declaration.NextTree());

				}
				stream_declaration.Reset();

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("entity_declaration", 7);
			LeaveRule("entity_declaration", 7);
			LeaveRule_entity_declaration();
	    }
	 	DebugLocation(64, 58);
		} finally { DebugExitRule(GrammarFileName, "entity_declaration"); }
		return retval;

	}
	// $ANTLR end "entity_declaration"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_type_declaration() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_type_declaration() {}

	// $ANTLR start "type_declaration"
	// lokad-codedsl\\Source\\MessageContracts.g:66:1: type_declaration : ID ( Modifier )? block -> ^( TypeToken ID block ( Modifier )? ) ;
	[GrammarRule("type_declaration")]
	private AstParserRuleReturnScope<object, IToken> type_declaration()
	{
		EnterRule_type_declaration();
		EnterRule("type_declaration", 8);
		TraceIn("type_declaration", 8);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken ID38 = default(IToken);
	    IToken Modifier39 = default(IToken);
	    AstParserRuleReturnScope<object, IToken> block40 = default(AstParserRuleReturnScope<object, IToken>);

	    object ID38_tree = default(object);
	    object Modifier39_tree = default(object);
	    RewriteRuleITokenStream stream_ID=new RewriteRuleITokenStream(adaptor,"token ID");
	    RewriteRuleITokenStream stream_Modifier=new RewriteRuleITokenStream(adaptor,"token Modifier");
	    RewriteRuleSubtreeStream stream_block=new RewriteRuleSubtreeStream(adaptor,"rule block");
		try { DebugEnterRule(GrammarFileName, "type_declaration");
		DebugLocation(66, 56);
		try
		{
			// lokad-codedsl\\Source\\MessageContracts.g:67:2: ( ID ( Modifier )? block -> ^( TypeToken ID block ( Modifier )? ) )
			DebugEnterAlt(1);
			// lokad-codedsl\\Source\\MessageContracts.g:67:4: ID ( Modifier )? block
			{
			DebugLocation(67, 4);
			ID38=(IToken)Match(input,ID,Follow._ID_in_type_declaration377);  
			stream_ID.Add(ID38);

			DebugLocation(67, 7);
			// lokad-codedsl\\Source\\MessageContracts.g:67:7: ( Modifier )?
			int alt7=2;
			try { DebugEnterSubRule(7);
			try { DebugEnterDecision(7, decisionCanBacktrack[7]);
			int LA7_0 = input.LA(1);

			if ((LA7_0==Modifier))
			{
				alt7 = 1;
			}
			} finally { DebugExitDecision(7); }
			switch (alt7)
			{
			case 1:
				DebugEnterAlt(1);
				// lokad-codedsl\\Source\\MessageContracts.g:67:7: Modifier
				{
				DebugLocation(67, 7);
				Modifier39=(IToken)Match(input,Modifier,Follow._Modifier_in_type_declaration379);  
				stream_Modifier.Add(Modifier39);


				}
				break;

			}
			} finally { DebugExitSubRule(7); }

			DebugLocation(67, 17);
			PushFollow(Follow._block_in_type_declaration382);
			block40=block();
			PopFollow();

			stream_block.Add(block40.Tree);


			{
			// AST REWRITE
			// elements: Modifier, block, ID
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 67:23: -> ^( TypeToken ID block ( Modifier )? )
			{
				DebugLocation(67, 26);
				// lokad-codedsl\\Source\\MessageContracts.g:67:26: ^( TypeToken ID block ( Modifier )? )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(67, 28);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(TypeToken, "TypeToken"), root_1);

				DebugLocation(67, 38);
				adaptor.AddChild(root_1, stream_ID.NextNode());
				DebugLocation(67, 41);
				adaptor.AddChild(root_1, stream_block.NextTree());
				DebugLocation(67, 47);
				// lokad-codedsl\\Source\\MessageContracts.g:67:47: ( Modifier )?
				if (stream_Modifier.HasNext)
				{
					DebugLocation(67, 47);
					adaptor.AddChild(root_1, stream_Modifier.NextNode());

				}
				stream_Modifier.Reset();

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("type_declaration", 8);
			LeaveRule("type_declaration", 8);
			LeaveRule_type_declaration();
	    }
	 	DebugLocation(67, 56);
		} finally { DebugExitRule(GrammarFileName, "type_declaration"); }
		return retval;

	}
	// $ANTLR end "type_declaration"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_member() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_member() {}

	// $ANTLR start "member"
	// lokad-codedsl\\Source\\MessageContracts.g:69:1: member : ( ID ID -> ^( MemberToken ID ID ) | ID -> ^( FragmentReference ID ) );
	[GrammarRule("member")]
	private AstParserRuleReturnScope<object, IToken> member()
	{
		EnterRule_member();
		EnterRule("member", 9);
		TraceIn("member", 9);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken ID41 = default(IToken);
	    IToken ID42 = default(IToken);
	    IToken ID43 = default(IToken);

	    object ID41_tree = default(object);
	    object ID42_tree = default(object);
	    object ID43_tree = default(object);
	    RewriteRuleITokenStream stream_ID=new RewriteRuleITokenStream(adaptor,"token ID");

		try { DebugEnterRule(GrammarFileName, "member");
		DebugLocation(69, 1);
		try
		{
			// lokad-codedsl\\Source\\MessageContracts.g:70:2: ( ID ID -> ^( MemberToken ID ID ) | ID -> ^( FragmentReference ID ) )
			int alt8=2;
			try { DebugEnterDecision(8, decisionCanBacktrack[8]);
			int LA8_0 = input.LA(1);

			if ((LA8_0==ID))
			{
				int LA8_1 = input.LA(2);

				if ((LA8_1==ID))
				{
					alt8 = 1;
				}
				else if (((LA8_1>=38 && LA8_1<=39)))
				{
					alt8 = 2;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 8, 1, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 8, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(8); }
			switch (alt8)
			{
			case 1:
				DebugEnterAlt(1);
				// lokad-codedsl\\Source\\MessageContracts.g:70:4: ID ID
				{
				DebugLocation(70, 4);
				ID41=(IToken)Match(input,ID,Follow._ID_in_member407);  
				stream_ID.Add(ID41);

				DebugLocation(70, 7);
				ID42=(IToken)Match(input,ID,Follow._ID_in_member409);  
				stream_ID.Add(ID42);



				{
				// AST REWRITE
				// elements: ID, ID
				// token labels: 
				// rule labels: retval
				// token list labels: 
				// rule list labels: 
				// wildcard labels: 
				retval.Tree = root_0;
				RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

				root_0 = (object)adaptor.Nil();
				// 70:10: -> ^( MemberToken ID ID )
				{
					DebugLocation(70, 13);
					// lokad-codedsl\\Source\\MessageContracts.g:70:13: ^( MemberToken ID ID )
					{
					object root_1 = (object)adaptor.Nil();
					DebugLocation(70, 15);
					root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(MemberToken, "MemberToken"), root_1);

					DebugLocation(70, 27);
					adaptor.AddChild(root_1, stream_ID.NextNode());
					DebugLocation(70, 30);
					adaptor.AddChild(root_1, stream_ID.NextNode());

					adaptor.AddChild(root_0, root_1);
					}

				}

				retval.Tree = root_0;
				}

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// lokad-codedsl\\Source\\MessageContracts.g:71:4: ID
				{
				DebugLocation(71, 4);
				ID43=(IToken)Match(input,ID,Follow._ID_in_member424);  
				stream_ID.Add(ID43);



				{
				// AST REWRITE
				// elements: ID
				// token labels: 
				// rule labels: retval
				// token list labels: 
				// rule list labels: 
				// wildcard labels: 
				retval.Tree = root_0;
				RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

				root_0 = (object)adaptor.Nil();
				// 71:7: -> ^( FragmentReference ID )
				{
					DebugLocation(71, 10);
					// lokad-codedsl\\Source\\MessageContracts.g:71:10: ^( FragmentReference ID )
					{
					object root_1 = (object)adaptor.Nil();
					DebugLocation(71, 12);
					root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(FragmentReference, "FragmentReference"), root_1);

					DebugLocation(71, 30);
					adaptor.AddChild(root_1, stream_ID.NextNode());

					adaptor.AddChild(root_0, root_1);
					}

				}

				retval.Tree = root_0;
				}

				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("member", 9);
			LeaveRule("member", 9);
			LeaveRule_member();
	    }
	 	DebugLocation(72, 1);
		} finally { DebugExitRule(GrammarFileName, "member"); }
		return retval;

	}
	// $ANTLR end "member"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_block() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_block() {}

	// $ANTLR start "block"
	// lokad-codedsl\\Source\\MessageContracts.g:75:1: block : lc= '(' ( member ( ',' member )* )? ')' ( representation )? -> ^( BlockToken[$lc,\"Block\"] ( member )* ( representation )? ) ;
	[GrammarRule("block")]
	private AstParserRuleReturnScope<object, IToken> block()
	{
		EnterRule_block();
		EnterRule("block", 10);
		TraceIn("block", 10);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken lc = default(IToken);
	    IToken char_literal45 = default(IToken);
	    IToken char_literal47 = default(IToken);
	    AstParserRuleReturnScope<object, IToken> member44 = default(AstParserRuleReturnScope<object, IToken>);
	    AstParserRuleReturnScope<object, IToken> member46 = default(AstParserRuleReturnScope<object, IToken>);
	    AstParserRuleReturnScope<object, IToken> representation48 = default(AstParserRuleReturnScope<object, IToken>);

	    object lc_tree = default(object);
	    object char_literal45_tree = default(object);
	    object char_literal47_tree = default(object);
	    RewriteRuleITokenStream stream_39=new RewriteRuleITokenStream(adaptor,"token 39");
	    RewriteRuleITokenStream stream_37=new RewriteRuleITokenStream(adaptor,"token 37");
	    RewriteRuleITokenStream stream_38=new RewriteRuleITokenStream(adaptor,"token 38");
	    RewriteRuleSubtreeStream stream_member=new RewriteRuleSubtreeStream(adaptor,"rule member");
	    RewriteRuleSubtreeStream stream_representation=new RewriteRuleSubtreeStream(adaptor,"rule representation");
		try { DebugEnterRule(GrammarFileName, "block");
		DebugLocation(75, 4);
		try
		{
			// lokad-codedsl\\Source\\MessageContracts.g:76:5: (lc= '(' ( member ( ',' member )* )? ')' ( representation )? -> ^( BlockToken[$lc,\"Block\"] ( member )* ( representation )? ) )
			DebugEnterAlt(1);
			// lokad-codedsl\\Source\\MessageContracts.g:76:9: lc= '(' ( member ( ',' member )* )? ')' ( representation )?
			{
			DebugLocation(76, 11);
			lc=(IToken)Match(input,37,Follow._37_in_block452);  
			stream_37.Add(lc);

			DebugLocation(77, 13);
			// lokad-codedsl\\Source\\MessageContracts.g:77:13: ( member ( ',' member )* )?
			int alt10=2;
			try { DebugEnterSubRule(10);
			try { DebugEnterDecision(10, decisionCanBacktrack[10]);
			int LA10_0 = input.LA(1);

			if ((LA10_0==ID))
			{
				alt10 = 1;
			}
			} finally { DebugExitDecision(10); }
			switch (alt10)
			{
			case 1:
				DebugEnterAlt(1);
				// lokad-codedsl\\Source\\MessageContracts.g:77:14: member ( ',' member )*
				{
				DebugLocation(77, 14);
				PushFollow(Follow._member_in_block467);
				member44=member();
				PopFollow();

				stream_member.Add(member44.Tree);
				DebugLocation(77, 21);
				// lokad-codedsl\\Source\\MessageContracts.g:77:21: ( ',' member )*
				try { DebugEnterSubRule(9);
				while (true)
				{
					int alt9=2;
					try { DebugEnterDecision(9, decisionCanBacktrack[9]);
					int LA9_0 = input.LA(1);

					if ((LA9_0==39))
					{
						alt9 = 1;
					}


					} finally { DebugExitDecision(9); }
					switch ( alt9 )
					{
					case 1:
						DebugEnterAlt(1);
						// lokad-codedsl\\Source\\MessageContracts.g:77:22: ',' member
						{
						DebugLocation(77, 22);
						char_literal45=(IToken)Match(input,39,Follow._39_in_block470);  
						stream_39.Add(char_literal45);

						DebugLocation(77, 26);
						PushFollow(Follow._member_in_block472);
						member46=member();
						PopFollow();

						stream_member.Add(member46.Tree);

						}
						break;

					default:
						goto loop9;
					}
				}

				loop9:
					;

				} finally { DebugExitSubRule(9); }


				}
				break;

			}
			} finally { DebugExitSubRule(10); }

			DebugLocation(78, 9);
			char_literal47=(IToken)Match(input,38,Follow._38_in_block486);  
			stream_38.Add(char_literal47);

			DebugLocation(78, 13);
			// lokad-codedsl\\Source\\MessageContracts.g:78:13: ( representation )?
			int alt11=2;
			try { DebugEnterSubRule(11);
			try { DebugEnterDecision(11, decisionCanBacktrack[11]);
			int LA11_0 = input.LA(1);

			if ((LA11_0==EXPLICIT))
			{
				alt11 = 1;
			}
			} finally { DebugExitDecision(11); }
			switch (alt11)
			{
			case 1:
				DebugEnterAlt(1);
				// lokad-codedsl\\Source\\MessageContracts.g:78:13: representation
				{
				DebugLocation(78, 13);
				PushFollow(Follow._representation_in_block488);
				representation48=representation();
				PopFollow();

				stream_representation.Add(representation48.Tree);

				}
				break;

			}
			} finally { DebugExitSubRule(11); }



			{
			// AST REWRITE
			// elements: representation, member
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 79:9: -> ^( BlockToken[$lc,\"Block\"] ( member )* ( representation )? )
			{
				DebugLocation(79, 12);
				// lokad-codedsl\\Source\\MessageContracts.g:79:12: ^( BlockToken[$lc,\"Block\"] ( member )* ( representation )? )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(79, 14);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(BlockToken, lc, "Block"), root_1);

				DebugLocation(79, 38);
				// lokad-codedsl\\Source\\MessageContracts.g:79:38: ( member )*
				while ( stream_member.HasNext )
				{
					DebugLocation(79, 38);
					adaptor.AddChild(root_1, stream_member.NextTree());

				}
				stream_member.Reset();
				DebugLocation(79, 46);
				// lokad-codedsl\\Source\\MessageContracts.g:79:46: ( representation )?
				if (stream_representation.HasNext)
				{
					DebugLocation(79, 46);
					adaptor.AddChild(root_1, stream_representation.NextTree());

				}
				stream_representation.Reset();

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("block", 10);
			LeaveRule("block", 10);
			LeaveRule_block();
	    }
	 	DebugLocation(80, 4);
		} finally { DebugExitRule(GrammarFileName, "block"); }
		return retval;

	}
	// $ANTLR end "block"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_representation() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_representation() {}

	// $ANTLR start "representation"
	// lokad-codedsl\\Source\\MessageContracts.g:82:1: representation : EXPLICIT STRING -> ^( StringRepresentationToken STRING ) ;
	[GrammarRule("representation")]
	private AstParserRuleReturnScope<object, IToken> representation()
	{
		EnterRule_representation();
		EnterRule("representation", 11);
		TraceIn("representation", 11);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken EXPLICIT49 = default(IToken);
	    IToken STRING50 = default(IToken);

	    object EXPLICIT49_tree = default(object);
	    object STRING50_tree = default(object);
	    RewriteRuleITokenStream stream_EXPLICIT=new RewriteRuleITokenStream(adaptor,"token EXPLICIT");
	    RewriteRuleITokenStream stream_STRING=new RewriteRuleITokenStream(adaptor,"token STRING");

		try { DebugEnterRule(GrammarFileName, "representation");
		DebugLocation(82, 57);
		try
		{
			// lokad-codedsl\\Source\\MessageContracts.g:83:2: ( EXPLICIT STRING -> ^( StringRepresentationToken STRING ) )
			DebugEnterAlt(1);
			// lokad-codedsl\\Source\\MessageContracts.g:83:4: EXPLICIT STRING
			{
			DebugLocation(83, 4);
			EXPLICIT49=(IToken)Match(input,EXPLICIT,Follow._EXPLICIT_in_representation532);  
			stream_EXPLICIT.Add(EXPLICIT49);

			DebugLocation(83, 13);
			STRING50=(IToken)Match(input,STRING,Follow._STRING_in_representation534);  
			stream_STRING.Add(STRING50);



			{
			// AST REWRITE
			// elements: STRING
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 83:20: -> ^( StringRepresentationToken STRING )
			{
				DebugLocation(83, 23);
				// lokad-codedsl\\Source\\MessageContracts.g:83:23: ^( StringRepresentationToken STRING )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(83, 25);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(StringRepresentationToken, "StringRepresentationToken"), root_1);

				DebugLocation(83, 51);
				adaptor.AddChild(root_1, stream_STRING.NextNode());

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("representation", 11);
			LeaveRule("representation", 11);
			LeaveRule_representation();
	    }
	 	DebugLocation(83, 57);
		} finally { DebugExitRule(GrammarFileName, "representation"); }
		return retval;

	}
	// $ANTLR end "representation"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_extern_declaration() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_extern_declaration() {}

	// $ANTLR start "extern_declaration"
	// lokad-codedsl\\Source\\MessageContracts.g:85:1: extern_declaration : EXTERN STRING ';' -> ^( ExternToken STRING ) ;
	[GrammarRule("extern_declaration")]
	private AstParserRuleReturnScope<object, IToken> extern_declaration()
	{
		EnterRule_extern_declaration();
		EnterRule("extern_declaration", 12);
		TraceIn("extern_declaration", 12);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken EXTERN51 = default(IToken);
	    IToken STRING52 = default(IToken);
	    IToken char_literal53 = default(IToken);

	    object EXTERN51_tree = default(object);
	    object STRING52_tree = default(object);
	    object char_literal53_tree = default(object);
	    RewriteRuleITokenStream stream_EXTERN=new RewriteRuleITokenStream(adaptor,"token EXTERN");
	    RewriteRuleITokenStream stream_41=new RewriteRuleITokenStream(adaptor,"token 41");
	    RewriteRuleITokenStream stream_STRING=new RewriteRuleITokenStream(adaptor,"token STRING");

		try { DebugEnterRule(GrammarFileName, "extern_declaration");
		DebugLocation(85, 50);
		try
		{
			// lokad-codedsl\\Source\\MessageContracts.g:86:5: ( EXTERN STRING ';' -> ^( ExternToken STRING ) )
			DebugEnterAlt(1);
			// lokad-codedsl\\Source\\MessageContracts.g:86:9: EXTERN STRING ';'
			{
			DebugLocation(86, 9);
			EXTERN51=(IToken)Match(input,EXTERN,Follow._EXTERN_in_extern_declaration557);  
			stream_EXTERN.Add(EXTERN51);

			DebugLocation(86, 16);
			STRING52=(IToken)Match(input,STRING,Follow._STRING_in_extern_declaration559);  
			stream_STRING.Add(STRING52);

			DebugLocation(86, 23);
			char_literal53=(IToken)Match(input,41,Follow._41_in_extern_declaration561);  
			stream_41.Add(char_literal53);



			{
			// AST REWRITE
			// elements: STRING
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 86:27: -> ^( ExternToken STRING )
			{
				DebugLocation(86, 30);
				// lokad-codedsl\\Source\\MessageContracts.g:86:30: ^( ExternToken STRING )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(86, 32);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(ExternToken, "ExternToken"), root_1);

				DebugLocation(86, 44);
				adaptor.AddChild(root_1, stream_STRING.NextNode());

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("extern_declaration", 12);
			LeaveRule("extern_declaration", 12);
			LeaveRule_extern_declaration();
	    }
	 	DebugLocation(86, 50);
		} finally { DebugExitRule(GrammarFileName, "extern_declaration"); }
		return retval;

	}
	// $ANTLR end "extern_declaration"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_template_declaration() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_template_declaration() {}

	// $ANTLR start "template_declaration"
	// lokad-codedsl\\Source\\MessageContracts.g:88:1: template_declaration : ID '=' STRING ';' -> ^( TemplateToken ID STRING ) ;
	[GrammarRule("template_declaration")]
	private AstParserRuleReturnScope<object, IToken> template_declaration()
	{
		EnterRule_template_declaration();
		EnterRule("template_declaration", 13);
		TraceIn("template_declaration", 13);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken ID54 = default(IToken);
	    IToken char_literal55 = default(IToken);
	    IToken STRING56 = default(IToken);
	    IToken char_literal57 = default(IToken);

	    object ID54_tree = default(object);
	    object char_literal55_tree = default(object);
	    object STRING56_tree = default(object);
	    object char_literal57_tree = default(object);
	    RewriteRuleITokenStream stream_42=new RewriteRuleITokenStream(adaptor,"token 42");
	    RewriteRuleITokenStream stream_41=new RewriteRuleITokenStream(adaptor,"token 41");
	    RewriteRuleITokenStream stream_ID=new RewriteRuleITokenStream(adaptor,"token ID");
	    RewriteRuleITokenStream stream_STRING=new RewriteRuleITokenStream(adaptor,"token STRING");

		try { DebugEnterRule(GrammarFileName, "template_declaration");
		DebugLocation(88, 55);
		try
		{
			// lokad-codedsl\\Source\\MessageContracts.g:89:5: ( ID '=' STRING ';' -> ^( TemplateToken ID STRING ) )
			DebugEnterAlt(1);
			// lokad-codedsl\\Source\\MessageContracts.g:89:9: ID '=' STRING ';'
			{
			DebugLocation(89, 9);
			ID54=(IToken)Match(input,ID,Follow._ID_in_template_declaration583);  
			stream_ID.Add(ID54);

			DebugLocation(89, 12);
			char_literal55=(IToken)Match(input,42,Follow._42_in_template_declaration585);  
			stream_42.Add(char_literal55);

			DebugLocation(89, 16);
			STRING56=(IToken)Match(input,STRING,Follow._STRING_in_template_declaration587);  
			stream_STRING.Add(STRING56);

			DebugLocation(89, 23);
			char_literal57=(IToken)Match(input,41,Follow._41_in_template_declaration589);  
			stream_41.Add(char_literal57);



			{
			// AST REWRITE
			// elements: ID, STRING
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 89:27: -> ^( TemplateToken ID STRING )
			{
				DebugLocation(89, 30);
				// lokad-codedsl\\Source\\MessageContracts.g:89:30: ^( TemplateToken ID STRING )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(89, 32);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(TemplateToken, "TemplateToken"), root_1);

				DebugLocation(89, 46);
				adaptor.AddChild(root_1, stream_ID.NextNode());
				DebugLocation(89, 49);
				adaptor.AddChild(root_1, stream_STRING.NextNode());

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("template_declaration", 13);
			LeaveRule("template_declaration", 13);
			LeaveRule_template_declaration();
	    }
	 	DebugLocation(89, 55);
		} finally { DebugExitRule(GrammarFileName, "template_declaration"); }
		return retval;

	}
	// $ANTLR end "template_declaration"
	#endregion Rules


	#region Follow sets
	private static class Follow
	{
		public static readonly BitSet _declaration_in_program121 = new BitSet(new ulong[]{0x404580842UL});
		public static readonly BitSet _modifier_declaration_in_declaration134 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _frag_declaration_in_declaration139 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _type_declaration_in_declaration144 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _entity_declaration_in_declaration149 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _namespace_declaration_in_declaration154 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _extern_declaration_in_declaration160 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _template_declaration_in_declaration165 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _using_declaration_in_declaration170 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _NAMESPACE_in_namespace_declaration184 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_namespace_declaration187 = new BitSet(new ulong[]{0x30000000000UL});
		public static readonly BitSet _40_in_namespace_declaration190 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_namespace_declaration192 = new BitSet(new ulong[]{0x30000000000UL});
		public static readonly BitSet _41_in_namespace_declaration197 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _USING_in_using_declaration227 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_using_declaration230 = new BitSet(new ulong[]{0x30000000000UL});
		public static readonly BitSet _40_in_using_declaration233 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_using_declaration235 = new BitSet(new ulong[]{0x30000000000UL});
		public static readonly BitSet _41_in_using_declaration240 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _CONST_in_frag_declaration264 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_frag_declaration266 = new BitSet(new ulong[]{0x40000000000UL});
		public static readonly BitSet _42_in_frag_declaration268 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_frag_declaration270 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_frag_declaration272 = new BitSet(new ulong[]{0x20000000000UL});
		public static readonly BitSet _41_in_frag_declaration274 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _IF_in_modifier_declaration301 = new BitSet(new ulong[]{0x1000000UL});
		public static readonly BitSet _Modifier_in_modifier_declaration303 = new BitSet(new ulong[]{0x40000000000UL});
		public static readonly BitSet _42_in_modifier_declaration305 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_modifier_declaration307 = new BitSet(new ulong[]{0x28000000000UL});
		public static readonly BitSet _39_in_modifier_declaration310 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_modifier_declaration312 = new BitSet(new ulong[]{0x28000000000UL});
		public static readonly BitSet _41_in_modifier_declaration316 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _INTERFACE_in_entity_declaration340 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_entity_declaration342 = new BitSet(new ulong[]{0x2000000000UL});
		public static readonly BitSet _block_in_entity_declaration344 = new BitSet(new ulong[]{0x80000000000UL});
		public static readonly BitSet _43_in_entity_declaration346 = new BitSet(new ulong[]{0x100404580840UL});
		public static readonly BitSet _declaration_in_entity_declaration348 = new BitSet(new ulong[]{0x100404580840UL});
		public static readonly BitSet _44_in_entity_declaration351 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _ID_in_type_declaration377 = new BitSet(new ulong[]{0x2001000000UL});
		public static readonly BitSet _Modifier_in_type_declaration379 = new BitSet(new ulong[]{0x2000000000UL});
		public static readonly BitSet _block_in_type_declaration382 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _ID_in_member407 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_member409 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _ID_in_member424 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _37_in_block452 = new BitSet(new ulong[]{0x4000080000UL});
		public static readonly BitSet _member_in_block467 = new BitSet(new ulong[]{0xC000000000UL});
		public static readonly BitSet _39_in_block470 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _member_in_block472 = new BitSet(new ulong[]{0xC000000000UL});
		public static readonly BitSet _38_in_block486 = new BitSet(new ulong[]{0x402UL});
		public static readonly BitSet _representation_in_block488 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _EXPLICIT_in_representation532 = new BitSet(new ulong[]{0x20000000UL});
		public static readonly BitSet _STRING_in_representation534 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _EXTERN_in_extern_declaration557 = new BitSet(new ulong[]{0x20000000UL});
		public static readonly BitSet _STRING_in_extern_declaration559 = new BitSet(new ulong[]{0x20000000000UL});
		public static readonly BitSet _41_in_extern_declaration561 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _ID_in_template_declaration583 = new BitSet(new ulong[]{0x40000000000UL});
		public static readonly BitSet _42_in_template_declaration585 = new BitSet(new ulong[]{0x20000000UL});
		public static readonly BitSet _STRING_in_template_declaration587 = new BitSet(new ulong[]{0x20000000000UL});
		public static readonly BitSet _41_in_template_declaration589 = new BitSet(new ulong[]{0x2UL});
	}
	#endregion Follow sets
}

} // namespace  MessageContracts 
